name: Bug Report
description: Report a bug in HodgePodge application launcher.
labels: ["bug"]
assignees:
  - the-ge
body:
  - type: checkboxes
    attributes:
      label: Prerequisites
      options:
        - label: I have already [searched in existing issues](https://github.com/the-ge/thege.hodgepodge.launcher/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.
          required: true
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to fill out this bug report!
        
        - **Write in English.** Reports in any other language will be closed without any consideration.
        - **Provide as much detail as possible.** If the issue cannot be reproduced, it cannot be fixed.

        ---

  - type: textarea
    id: what-happened
    attributes:
      label: Describe the bug and add attachments
      description: What went wrong? If possible, add screenshots, error logs or screen recordings to help explain your problem.
    validations:
      required: true
  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected behavior
      description: Explain what you expected to happen instead.
    validations:
      required: false
  - type: textarea
    id: steps-reproduce
    attributes:
      label: Steps to reproduce
      description: List the exact steps to reproduce the issue.
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: false
  - type: textarea
    attributes:
      label: Environment (versions)
      description: |
        You can find this information in System Configuration > About this system or `kinfo` in CLI.
        Examples:
          - **Hodgepodge Launcher**: 2.0.8
          - **KDE Plasma**: 6.5.3
          - **KDE Frameworks**: 6.20.0
          - **Qt**: 6.10.1
          - **Kernel Version:** 6.12.61-1-MANJARO (64-bit)
          - **Graphics Platform**: X11
      value: |
          - Hodgepodge Launcher:
          - KDE Plasma:
          - KDE Frameworks:
          - Qt:
          - Kernel Version:
          - Graphics Platform:
      render: markdown
    validations:
        required: true
